apiVersion: apps/v1
kind: Deployment
metadata:
  name: molpredict-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: molpredict-worker
  template:
    metadata:
      labels:
        app: molpredict-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["rq", "worker", "--url", "redis://redis:6379"]
